### ISSUE TITLE
[BUG] Home Page: text appears off screen, but no ability to scroll

### ISSUE THREAD

**Issue by smashedTuba28** [YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-frontend#104]
Upon initial loading of the website on my laptop the "Visualization" button and text appear off screen.
There is no ability to scroll down on the page. The only way to see the button in full is to zoom out. 

![image](https://user-images.githubusercontent.com/48068139/107562298-9d72e900-6bad-11eb-9d73-2a4b6e9d6a8a.png)
Normal Zoom of 100%

![image](https://user-images.githubusercontent.com/48068139/107562248-8b914600-6bad-11eb-8d92-ddb92f1b535f.png)
Zoomed out at 90%

**Comment by Walrussuit101** [comment]
Thank you for reporting this @smashedTuba28 !!
